### ISSUE TITLE
missing dependency curl

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#12]
a load with stack build from a cloned a727a02  on debian  - stretch fails lacking a curl c library.

Cabal means the curl C library, which must be installed by either the packages
libcurl4-openssl-dev or libcurl4-gnutls-dev.   
[see](https://mail.haskell.org/pipermail/haskell-cafe/2012-August/102863.html)

next it also requires libssl1.0-dev, libpq-dev and libfcgi-dev; but then it installs ok.

it would be nice to include these hints in the installation instructinons.

**Comment by tdammers** [comment]
The `README` mentions libcurl, libpq and libfcgi; I just added libssl. Due to the way distros and distro packaging work, it is unfortunately not possible to provide a definitive list.

I also plan to provide "feature toggles" (in the form of Cabal switches) that would allow you to enable certain things (e.g. the MySQL backend), which in turn would make it possible to build without most of those dependencies. #14 details this.

**Comment by andrewufrank** [comment]
thank you - I did not read the readme carefully enough. 
feature togles (or breaking into more than one package) would be welcome - my interest is specifically in bake to produce static sites - would be welcome!
