### ISSUE TITLE
blank lines 

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#18]
A template like 
````
{% extends "base.html" %}
{% block title %}{{ SITENAME }}{% endblock %}

{% block content %}
<div class="row">
 <div class="col-md-8">
  <h1>{{ SITENAME }}</h1>
  {% for article in articles %}
   <h2><a href="/{{ article.slug }}.html">{{ article.title }}</a></h2>
   <label>Posted on <strong>{{ article.date }}</strong></label>
   {{ article.content|truncate(110) }}
  {% else %}
   No posts yet 4!
  {% endfor %}
 </div>
</div>
{% endblock %}
````
throws error 
````
sprinkles -serve 5000
ServeProject (ServerConfig {scBackendCache = [], scDriver = WarpDriver (Just 5000), scLogger = Nothing, scSessions = SessionConfig {sessCookieName = "ssid", sessCookieSecure = True, sessExpiration = NeverExpire, sessDriver = NoSessionDriver}, scRootDir = ""})
In 'index.html': line 4, column 1: unexpected " "
expecting "{%-"
````
the same template wihout the blank line is ok. Could you check the parser?

**Comment by tdammers** [comment]
Ah yes, that's a quirk in Ginger, which I believe is fixed in the most recent Ginger release (though the most recent Sprinkles doesn't use that yet).

The problem boils down to the fact that the blank line is parsed as an HTML literal, which is illegal at the top level in an inheritance child template (i.e., a template that starts with an `{%extends %}` directive). IIRC, this has been fixed in Ginger, skipping blank lines at the top level in child templates; in the meantime, a simple workaround is to use `{%- -%}` (note the dash) for top-level tags; these "eat" whitespace before and after, and thus don't produce any top-level whitespace literals.
