### ISSUE TITLE
date included in page

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#22]
I would like to add a line at the bottom the master.page stating that the content is produced with sprinkels and include the date when the baking was done. 
I tried
```
        Produced with Sprinkles on {{ datetime.date.today() }}.
```
but nothing is printed. My understanding of jinja2 is very limited; suggestions I received required to include some python code, but I am sure you know a solution which can be used without adding python code somewhere.

**Comment by tdammers** [comment]
You do realize that Sprinkles isn't written in Python though, and that it
doesn't use actual jinja2, right? Because this means that splicing
arbitrary Python code into your templates cannot possibly work.

I don't know off the top of my head which exact date/time functionality is
available so it's possible that a "current date time" value is available,
either through Ginger itself, or through something Sprinkles adds. I'll
take a look tomorrow, see if I can cough anything up.

If nothing is available, a brute workaround would be to have a subprocess
data item in your project.yml that prints a suitable datetime string, and
then just reference that in your template.

**Comment by tdammers** [comment]
OK, I took a quick peek. Neither Sprinkles nor Ginger have a "current time" value or function available anywhere, but actually neither does Jinja2. I completely agree that this might be useful; in the meantime, here's an example implementation of the workaround:

-- project.yml --
```yaml
rules:
  - pattern: '/'
    template: 'main.html'
    data:
      - now:
          type: subprocess
          cmd: ['date']
          mime-type: 'text/plain'
```

Now you can write `{{ date }}` in your templates, and it'll spit out the date/time from when the rule was matched.
